### ISSUE TITLE
Union implementation

### ISSUE THREAD

**Issue by niteria** [phadej/insert-ordered-containers#10]
You're probably aware of this, but just in case you weren't.

Your `union` implementation overflows `Int` for:
```
iterate (\a -> union a a) a
```

I needed to implement something like your package for GHC and that's what I ended up with:

https://phabricator.haskell.org/diffusion/GHC/browse/master/compiler/utils/UniqDFM.hs;20c06143a7bfc6548351e610350a8e1c0d8a0bb9$128-136

**Comment by phadej** [comment]
Hmm I guess I can fix it by re-indexing after `union`.
