### ISSUE TITLE
Bump base and lens bounds to support GHC-9.4.1

### ISSUE THREAD

**Issue by TeofilC** [phadej/insert-ordered-containers#47]
I've checked that this package builds with base-4.17 and lens-5.2

**Comment by ysangkok** [comment]
@phadej Any chance of bumping these? Much appreciated.

**Comment by phadej** [comment]
![Screenshot from 2022-08-23 17-29-16](https://user-images.githubusercontent.com/51087/186184992-aa77499c-a50f-460f-bb60-4e5cdeb16a6a.png)

... in due time

**Comment by phadej** [comment]
... in fact as this package was created for `swagger2` (and now also `openapi3` uses it), I'll be happy to transfer maintenership to `swagger2` and `openapi3` maintainers. I don't use this package myself, so it's very low in my priority lists.

**Comment by TeofilC** [comment]
Cheers!
