### ISSUE TITLE
tasty-1.5 not accepted

### ISSUE THREAD

**Issue by ysangkok** [phadej/insert-ordered-containers#55]
According to CONTRIBUTING.md , I am not making a PR.

[the cabal file](https://hackage.haskell.org/package/insert-ordered-containers-0.2.5.3/src/insert-ordered-containers.cabal) excludes tasty-1.5. 

See also:

* https://github.com/commercialhaskell/stackage/issues/7111

**Comment by phadej** [comment]
As it's just test dependency, I won't make revisions just for them.
